version: '3.8'
services:
  demurrage-calculator:
    build: .
    environment:
      - PORT=8006
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKERS=4
      - LOG_LEVEL=info
      - MAX_REQUESTS=10000
    ports:
      - "8006:8006"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
