services:
  - type: web
    name: demurrage-calculator
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
